import type { Metadata } from "next";
import { Lato, Comfortaa } from "next/font/google";
import "modern-normalize/modern-normalize.css";
import "./globals.css";
import LogoSprite from "@/components/Logo/LogoSprite";
import UiSprite from "@/components/Icon/UiSprite";

const lato = Lato({
  variable: "--font-lato",
  display: "swap",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  display: "swap",
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${comfortaa.variable}`}>
        <LogoSprite />
        <UiSprite />
        {children}
      </body>
    </html>
  );
}
