import type { Metadata } from "next";
import { Lato, Comfortaa } from "next/font/google";
import SideBar from "@/components/SideBar/SideBar";
import Header from "@/components/Header/Header";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";
import "./globals.css";
import css from "./page.module.css";
import "modern-normalize/modern-normalize.css";

const lato = Lato({
  variable: "--font-lato",
  display: "swap",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  display: "swap",
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${comfortaa.variable}`}>
        <div className={css.container}>
          <SideBar />
          <div className={css.pageWrapper}>
            <Breadcrumbs />
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
